const ADD_PHOTO ='ADD_PHOTO';
const ADD_ISLOGIN ='ADD_ISLOGIN';
const ADD_LIKED_BY_USERS ='ADD_LIKED_BY_USERS';
const REMOVE_LIKED_BY_USERS ='REMOVE_LIKED_BY_USERS';
const ADD_MUTUAL_USERS ='ADD_MUTUAL_USERS';
const ADD_USERS_DASHBOARD = 'ADD_USERS_DASHBOARD'

export {ADD_PHOTO, ADD_ISLOGIN, ADD_LIKED_BY_USERS, ADD_MUTUAL_USERS, REMOVE_LIKED_BY_USERS,ADD_USERS_DASHBOARD}
