const ADD_PHOTO = "ADD_PHOTO";
const ADD_ISLOGIN = "ADD_ISLOGIN";
const ADD_LIKED_BY_USERS = "ADD_LIKED_BY_USERS";
const REMOVE_LIKED_BY_USERS = "REMOVE_LIKED_BY_USERS";
const ADD_MUTUAL_USERS = "ADD_MUTUAL_USERS";
const EDIT_PROFILE = "EDIT_PROFILE";
const EDIT_PROFILE_EDIT = "EDIT_PROFILE_EDIT";
const ADD_USER = "ADD_USER";

export {
  ADD_PHOTO,
  ADD_ISLOGIN,
  ADD_LIKED_BY_USERS,
  ADD_MUTUAL_USERS,
  REMOVE_LIKED_BY_USERS,
  EDIT_PROFILE,
  EDIT_PROFILE_EDIT,
  ADD_USER
};
